services:
  - docker

env:
  - SG_ENV=production

before_install:
  # Configure git
  - git config --global user.name "PlaceOS"
  - git config --global user.email support@place.tech

script:
  - ./test