dist: xenial
language: crystal

services: redis-server

env:
  - SG_ENV=production

before_install:
  # Configure git
  - git config --global user.name "PlaceOS"
  - git config --global user.email support@place.tech

install:
  # Install the latest version of LibSSH2
  - wget https://launchpad.net/ubuntu/+source/libgpg-error/1.32-1/+build/15118612/+files/libgpg-error0_1.32-1_amd64.deb
  - sudo dpkg -i libgpg-error0_1.32-1_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/libgcrypt20/1.8.3-1ubuntu1/+build/15106861/+files/libgcrypt20_1.8.3-1ubuntu1_amd64.deb
  - sudo dpkg -i libgcrypt20_1.8.3-1ubuntu1_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/libssh2/1.8.0-2/+build/15151524/+files/libssh2-1_1.8.0-2_amd64.deb
  - sudo dpkg -i libssh2-1_1.8.0-2_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/libgpg-error/1.32-1/+build/15118612/+files/libgpg-error-dev_1.32-1_amd64.deb
  - sudo dpkg -i libgpg-error-dev_1.32-1_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/libgcrypt20/1.8.3-1ubuntu1/+build/15106861/+files/libgcrypt20-dev_1.8.3-1ubuntu1_amd64.deb
  - sudo dpkg -i libgcrypt20-dev_1.8.3-1ubuntu1_amd64.deb
  - wget https://launchpad.net/ubuntu/+source/libssh2/1.8.0-2/+build/15151524/+files/libssh2-1-dev_1.8.0-2_amd64.deb
  - sudo dpkg -i libssh2-1-dev_1.8.0-2_amd64.deb
  - shards install

script:
  # Specs
  - crystal spec --error-trace -v
  # Formatter
  - crystal tool format --check
