version: "3.7"

# YAML Anchors

x-deployment-env: &deployment-env
  ENV: ${ENV:-development}
  SG_ENV: ${SG_ENV:-development}
  TZ: $TZ

x-redis-client-env: &redis-client-env
  REDIS_URL: ${REDIS_URL:-redis://redis:6379}

services:
  test:
    image: placeos/service-spec-runner:${CRYSTAL_VERSION:-1.2.2}
    volumes:
      - ${PWD}/spec:/app/spec
      - ${PWD}/src:/app/src
      - ${PWD}/lib:/app/lib
      - ${PWD}/shard.lock:/app/shard.lock
      - ${PWD}/shard.yml:/app/shard.yml
      - ${PWD}/coverage:/app/coverage
    depends_on:
      - redis
    environment:
      # Service Hosts
      << : *redis-client-env
      # Environment
      GITHUB_ACTION: ${GITHUB_ACTION-}
      << : *deployment-env

  redis:
    image: eqalpha/keydb
    restart: always
    hostname: redis
    environment:
      TZ: $TZ
