FROM crystallang/crystal:0.35.1-alpine

WORKDIR /app

# Set the commit through a build arg
ARG PLACE_COMMIT="DEV"

# Install the latest version of LibSSH2, ping
RUN apk add --no-cache libssh2 libssh2-dev iputils

# Add trusted CAs for communicating with external services
RUN apk update && apk add --no-cache ca-certificates tzdata && update-ca-certificates

# Create a non-privileged user
# defaults are appuser:10001
ARG IMAGE_UID="10001"
ENV UID=$IMAGE_UID
ENV USER=appuser

# See https://stackoverflow.com/a/55757473/12429735RUN
RUN adduser \
    --disabled-password \
    --gecos "" \
    --home "/nonexistent" \
    --shell "/sbin/nologin" \
    --no-create-home \
    --uid "${UID}" \
    "${USER}"

COPY shard.yml /app
COPY shard.lock /app
RUN PLACE_COMMIT=$PLACE_COMMIT \
    shards install --production

# Add source last for efficient caching
COPY src /app/src

RUN crystal build --error-trace --release --debug -o bin/compiler src/placeos-compiler.cr

# These provide certificate chain validation where communicating with external services over TLS
ENV SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Use an unprivileged user.
RUN chown appuser:appuser -R /app
USER appuser:appuser

CMD ["/app/bin/compiler"]