name: CI

on:
  push:
  schedule:
    - cron: "0 6 * * 1"

jobs:
  style:
    uses: PlaceOS/.github/.github/workflows/crystal-style.yml@main

  test:
    uses: PlaceOS/.github/.github/workflows/containerised-test.yml@main
    with:
      cache_shards: false
